# Generated by Django 5.2.7 on 2025-10-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="jogos_imagens/")),
                ("titulo", models.CharField(max_length=100)),
                ("genero", models.CharField(max_length=50)),
                ("lancamento", models.DateField()),
                ("descricao", models.TextField(blank=True)),
            ],
        ),
    ]
